### ISSUE TITLE
Error: Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/Firely.Fhir.Packages#83]
Error thrown when calling the package resolver on something from disk. 
Hopefully we can reproduce this, otherwise, here is the stack trace from @FoppeCrezee 

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Length cannot be less than zero. (Parameter 'length'))
 ---> Firely.Fhir.Packages.PackageRestoreException: Length cannot be less than zero. (Parameter 'length')
   --- End of inner exception stack trace ---
   at Firely.Fhir.Packages.PackageRestorer.Restore()
   at Firely.Fhir.Packages.PackageRestoreExtensions.Restore(PackageContext context)
   at Firely.Fhir.Packages.FhirPackageSource.installPackageFromPath(PackageContext scope, String path)
   at Firely.Fhir.Packages.FhirPackageSource.createContext(String scopePath, PackageClient client, String[] filePaths, Boolean localCache)
   at Firely.Fhir.Packages.FhirPackageSource.createPackageContextFromFilesAsync(String[] paths)
   at Hl7.Fhir.Utility.TaskHelper.Await[T](Func`1 asyncFunc)
   at Firely.Fhir.Packages.FhirPackageSource.<>c__DisplayClass2_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Firely.Fhir.Packages.FhirPackageSource.ResolveByCanonicalUriAsyncAsString(String uri)
   at Firely.Fhir.Packages.FhirPackageSource.ResolveByCanonicalUriAsync(String uri)
   at Hl7.Fhir.Specification.Source.ResourceResolverExtensions.FindStructureDefinitionAsync(IAsyncResourceResolver resolver, String uri)
   at FHIRDataGenerator.Generator.GenerateResource() in C:\Users\Foppe\Documents\Projects\Furore\FhirDataGenerator\FHIRDataGenerator\FHIRDataGenerator\Generator.cs:line 21
   at Program.Main(String[] args) in C:\Users\Foppe\Documents\Projects\Furore\FhirDataGenerator\FHIRDataGenerator\FHIRDataGenerator\Program.cs:line 29
   at Program.<Main>(String[] args)
```
```

var test = "C:\\Users\\Foppe\\Documents\\Projects\\Furore\\FhirDataGenerator\\FHIRDataGenerator\\FHIRDataGenerator\\Input\\nictiz.fhir.nl.stu3.zib2017-2.2.16.tgz";
 var package = $"{packageName}@{packageVersion}";
 //FhirPackageSource resolver = new(ModelInfo.ModelInspector, "https://packages.simplifier.net/", new string[] { package });
 FhirPackageSource resolver = new(ModelInfo.ModelInspector, new string[] { test });
```

**Comment by mmsmits** [comment]
possible duplicate of #71
